server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://dpg-d32aq53uibrs739mpiqg-a.oregon-postgres.render.com/catalogs_hekw
    password: GNdw5EdOFNMHQ2HQkAcN1cqEiPRBfePF
    username: aaron
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    dll-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect